# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoPlayBack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Brightcove-Player-SDK/dynamic'
  # Pods for VideoPlayBack

end
